name: Comhon\Config
is_main: true
properties:
    -
        name: manifest_format
        is_private: true
        default: json
        enum:
            - json
            - xml
            - yaml
        inheritance-: Comhon\Manifest\Property\String
    -
        name: autoload
        is_private: true
        model: Autoload
        inheritance-: Comhon\Manifest\Property\Object
    -
        name: regex_list
        is_private: true
        inheritance-: Comhon\Manifest\Property\String
    -
        name: date_time_format
        is_private: true
        inheritance-: Comhon\Manifest\Property\String
    -
        name: database
        is_private: true
        model: DbOpt
        inheritance-: Comhon\Manifest\Property\Object
    -
        name: sql_table
        is_private: true
        inheritance-: Comhon\Manifest\Property\String
    -
        name: sql_database
        is_private: true
        inheritance-: Comhon\Manifest\Property\String
    -
        name: cache_settings
        is_private: true
        inheritance-: Comhon\Manifest\Property\String
    -
        name: request_collection_limit
        inheritance-: Comhon\Manifest\Property\Integer
    -
        name: allow_complex_request
        inheritance-: Comhon\Manifest\Property\Boolean
    -
        name: account_model
        inheritance-: Comhon\Manifest\Property\String
version: '3.0'
types:
    -
        name: DbOpt
        properties:
            -
                name: charset
                inheritance-: Comhon\Manifest\Property\String
            -
                name: timezone
                inheritance-: Comhon\Manifest\Property\String
    -
        name: Autoload
        properties:
            -
                name: manifest
                is_associative: true
                values:
                    name: manifest
                    inheritance-: Comhon\Manifest\Value\String
                inheritance-: Comhon\Manifest\Property\Array
            -
                name: serialization
                is_associative: true
                values:
                    name: serialization
                    inheritance-: Comhon\Manifest\Value\String
                inheritance-: Comhon\Manifest\Property\Array
            -
                name: options
                is_associative: true
                values:
                    name: options
                    inheritance-: Comhon\Manifest\Value\String
                inheritance-: Comhon\Manifest\Property\Array
